# Generated by Django 3.0.4 on 2020-06-28 11:49

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0011_auto_20200625_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
