# Generated by Django 3.0.7 on 2020-06-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200619_1042'),
        ('home', '0007_auto_20200618_2210'),
        ('home', '0006_auto_20200619_2101'),
    ]

    operations = [
    ]
