# Generated by Django 3.0.7 on 2020-06-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('about', '0003_aboutpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='banner_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
