# Generated by Django 3.0.7 on 2020-06-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20200620_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
    ]
