# Generated by Django 3.0.7 on 2020-06-23 21:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20200621_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
