# Generated by Django 3.0.7 on 2020-06-23 22:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200623_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
